version: '3.1'
services:
  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
        - POSTGRES_DB=stats-db
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  main-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main_db
      - STATS_SERVER_URL=http://stats-server:9090
      - POSTGRES_USER=root
      - POSTGRES_PASS=root

  main-db:
    image: postgres:13.7-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root