version: '3.1'
services:
  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
        - POSTGRES_DB=stats-db
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root


  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASS=ewm_pass

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6551:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_pass